### ISSUE TITLE
can't change animation after moving character

### ISSUE THREAD

**Issue by tkcbets** [Eusth/PlayClubVR#11]
Since v0.8.2 I have been unable to change animation after moving the character.  In older releases you could grab the movement orb at the feet of the character and hold trigger and move character around, then change animations at will

now you have to go to conductor/maestro mode to be able to grab the movement orb at all, and once you move it, you can't change animation.  It seems the head will sort of move but not the whole body, even after leaving conductor mode

also even if I select the animation I want and try to move the character around, it gets glitchy with the animation, where it did not do that before 0.8.2

**Comment by Eusth** [comment]
I'll take a look, thanks for the heads up!

One note though: make sure *not* to use the conventional IK menu to enable the handles. Only activate the handles using the conductor tool.

**Comment by Eusth** [comment]
OK, I see what's the problem.

When you start the conductor tool, IK mode automatically activates and messes with the animations. I made this automatic for users who want to move the limbs of their characters, but for cases like yours where you only want to move the character, this is a little overkill.

I'll see if I can find a workaround.
