### ISSUE TITLE
If mirroring is disabled, vive controller cursor will get stuck on certain UI options

### ISSUE THREAD

**Issue by wicked1313** [Eusth/PlayClubVR#12]
Ex. Positions. Seems to work every time. Reselecting the blank game screen on your windows desktop resolves the issue until you click on the wrong thing again.

**Comment by Eusth** [comment]
Which options are causing the problem? Are you using fullscreen mode?

**Comment by wicked1313** [comment]
I'm actually not sure now, I thought it was not turning on mirroring mode, but I had it happen with mirroring mode on later. I'll try and repeat it a few times tomorrow and try and let you know what exact settings seem to be causing it.

**Comment by Eusth** [comment]
FYI: When the window loses focus, UI elements will not react anymore. I'm trying to confine the cursor but it doesn't always work.

Might be the issue here.

**Comment by wicked1313** [comment]
It appears after some testing that if you happen to click the part of the window corresponding to the location the little always on steamVR UI tab is under, it will click steamVR instead and cause the window to lose focus. This was the whole source of the bug after all, nothing to do with mirroring.

**Comment by Eusth** [comment]
Thanks for clearing this up! In that case I recommend turning off the *always on top* option in SteamVR.
