### ISSUE TITLE
Feature idea

### ISSUE THREAD

**Issue by Carrott2016** [Eusth/PlayClubVR#2]
Hi,
first, thank you for your excellent work! This mod works amazingly well!

As the references to the skin files (e.g. tatoos) from the skin texture mod are not saved with the character in PlayClub customization mode, it would be great to be able to use the SkinTexture Mod in PlayClubVR as well to load customized textures. The hotkey "J" for the texture mod menu seems not to work in PlayClubVR. Tested with latest Version 0.7

**Comment by Eusth** [comment]
Funnily, just when I was trying to improve support for other mods, Hongfire went down. ;)

I might look into it when they're back up.

**Comment by Eusth** [comment]
Fixed by now.
