### ISSUE TITLE
Game tries to find executable that doesn't exist, hence not launching

### ISSUE THREAD

**Issue by cetanu** [Eusth/PlayClubVR#24]
Downloaded a fresh copy of the latest release

Run the executable (PlayClubVR.exe)

Error: Can't find $DIRECTORY/PlayClub.exe

No such file exists... Tried renaming the run executable to the same name, get no error, but also nothing happens at all.

Expected behavior?

**Comment by Eusth** [comment]
You have to install the actual game first.

**Comment by cetanu** [comment]
Huh. -_- I mistakenly thought this *was* the game. I will go do that then.
