### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by Eusth** [Eusth/PlayClubVR#3]
A few comments re: controls:

1. Changing height and scale has to be more intuitive
2. It should be easier to move around characters

**Comment by supermanscottbristol** [comment]
Is there somewhere that lists what all the controls and setup options are please?

**Comment by Eusth** [comment]
Sadly, I didn't get around to making a comprehensive list, but this is what's available:

*Key shortcuts:*
http://www.hongfire.com/forum/forum/hentai-lair/hf-modding-translation/play-club-mods/419042-playclubvr-openvr

*Vive controllers:*
Hold the app menu button at any time in the game.

*Gamepad:*
No documentation as of now.

**Comment by kreschnav** [comment]
If the height/scale were to be decoupled from the teleport (maybe mapped to the grip buttons?), would it be possible to have the camera's height/scale change _as_ the controller is being moved? I find having to teleport when I just want to change the height/scale to be a bit cumbersome.

**Comment by Eusth** [comment]
Sure, if you can propose a good way to integrate it  into the existing controls.

I'd still only show the play area to prevent motion sickness.

**Comment by supermanscottbristol** [comment]
How about left grip goes up, right grip goes down

**Comment by Eusth** [comment]
Unfortunately, it doesn't seem to be possible to tell left and right apart.
Also, the grip button is already used to reset your play area.
