### ISSUE TITLE
Control Idea

### ISSUE THREAD

**Issue by ciphray** [Eusth/PlayClubVR#4]
Someone had used your controller source to add a moveable GUI to CM3D2 which allowed you to move the GUI to any position within reach and it remained there.

Is it possible for you to have a hybrid of sorts of yours and theirs?

For instance, say you move your controller to a specific location, squeeze the trigger and the display decouples itself from the controller remains in place in your room space, trackpad still controls the mouse
then when you want the screen to revert to the controller you squeeze the grip and it returns to it's normal behavior

**Comment by Eusth** [comment]
Yes, this feature will come in one of the next updates. :)
(Tracked at https://github.com/Eusth/VRGIN/issues/2)
