### ISSUE TITLE
'jiggle' broken?

### ISSUE THREAD

**Issue by tkcbets** [Eusth/PlayClubVR#5]
on v0.8.2 suddenly I can no longer jiggle breasts and such with my vive controllers in studio.

also trying out the new detach/resize menu feature - I am able to detach the menu but can't seem to move/resize it with both controllers.  tried grip buttons and other button combos but it seems to have no effect

**Comment by Eusth** [comment]
The next version will slightly change the boob physics anyway -- I'll look into it while I'm at it.

You have to point at the menu with both controllers and then hold the trigger button on both controllers.

**Comment by tkcbets** [comment]
seems to work in latest release.  also finally figured out I was supposed to use the little 'lasers' coming out of the controllers to point at the menus to move/resize them.
