### ISSUE TITLE
Keyboard Controls not working

### ISSUE THREAD

**Issue by thyujiok** [Eusth/PlayClubVR#6]
Hello!

Everything is working fine (Vive Controller and video), the game is not recieving any input from the keyboard for keyboard shortcuts.

Is there something i need to do to enable them? or is this a known issue?

Thanks!

**Comment by Eusth** [comment]
Most keyboard shortcuts are only available in seated mode. To switch, press Ctrl+c twice.
In addition, the game window has to be focused for the keyboard to work.
