### ISSUE TITLE
Help , I can't generate Exe files by VS2015

### ISSUE THREAD

**Issue by armstrong1972** [Eusth/PlayClubVR#8]
Hi Eusth ：

   I downloaded all source code by Git and compiled the solution, It passed.
   But no Exe files were generated . I double checked the "OutputType" in 4 projects , they are all "Library" . So only DLL files were generated.

   Pls help me : how can I generate Exe files .

Thanks 

Armstrong Li
Beijing China

**Comment by Eusth** [comment]
Hey there!

First off: the .exe Files are only used to patch the DLLs and are not really part of PlayClubVR. You can just use those that come [with any of the releases](https://github.com/Eusth/PlayClubVR/releases). I simply haven't added them to the repository yet.

If you want to build it all yourself, check out [this project](https://github.com/Eusth/Illusion-Plugins/tree/master/QuietLauncher) and rename the built file to *PlayClubVR.exe*.

**Comment by armstrong1972** [comment]
Greate, thanks Eusth .
